name: Laravel CI

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Copy assets
        run: |
          npm install
          npm run production

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, fileinfo, pdo_sqlite
          coverage: none

      - name: Install Dependencies (PHP vendors)
        run: composer install --dev -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Copy ENV Laravel Configuration for CI
        run: composer run post-root-package-install
      - name: Generate key
        run: php artisan key:generate
      - name: Execute tests (Unit and Feature tests)
        run: php artisan test
